fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  # - repo: https://github.com/ambv/black
  #   rev: 23.1.0
  #   hooks:
  #   - id: black
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.18.0
    hooks:
    - id: ansible-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1024']
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: pretty-format-json
      # https://pre-commit.com/#regular-expressions
      exclude: |
          (?x)^(
              .devcontainer/devcontainer.json|
              .vscode/launch.json|
              .vscode/settings.json
          )$
      args: ['--autofix', '--indent=2', '--no-sort-keys']
    - id: requirements-txt-fixer
    # - id: trailing-whitespace
